### ISSUE TITLE
Issues with documentation

### ISSUE THREAD

**Issue by ThrownLemon** [AmericanPresidentJimmyCarter/yasd-discord-bot#13]
Firstly love your work, great project!

Just a few things/issues I came across following the documentation for native install.

1. Got an error that the version of Jax was too old but was able to fix that by not specifying the version, which installed the latest and seems to work fine. `pip install jax`

2. I had to clone the original SwinIR repo because upscaling was throwing an error about missing **main_test_swinir.py** script and **models/network_swinir.py** (this was since you added the buttons, previously did not have this issue.)

3. Not related to your code but updating to python 10.3 on Ubuntu 20.04.5 LTS was a massive pain but I eventually got it working.... More of an FYI for Ubuntu users.

**Comment by AmericanPresidentJimmyCarter** [comment]
Thank you!

1. Okay, that was an issue exclusively for DALLE-MEGA I think. Jina installs the software for all models by default. You can turn them on/off with `flow_parser.py` flags -- they'll just magically work and instead of 4 images you'll get 4 from Stable Diffusion and 4 from DALLE-MEGA, ranked automatically for quality.
2. That's weird, I don't think jina has pushed to that upstream in a while and I haven't personally had that issue.
3. Long term once dalle-flow's docker image is finally fixed (trying to work on that this week), I will be migrating to docker-compose installs that should make everything much easier. Sorry for the pain in updating. I can also add more instructions for installation as time goes on.

Unfortunately I wish I had more time to work on this, but I only really get time after my dayjob to work on this stuff. If you want to PR an `installation.MD` it would always be appreciated too. :)

**Comment by ThrownLemon** [comment]
All good, thanks for your efforts! 

Just an update:  

On point 2: I found the issue, I just cloned the wrong repo.
On point 3: Ubuntu 22.04.1 LTS worked out of the box as it has a more recent version of python.
