### ISSUE TITLE
[Feature Request] Button to rerun image command with new seeds

### ISSUE THREAD

**Issue by aaronsantiago** [AmericanPresidentJimmyCarter/yasd-discord-bot#27]
Title. All the parameters should be the same but we should be able to run it again to see more variations.

It would be nice if the same button existed on riffs as well to create more riffs from the same base image.

**Comment by AmericanPresidentJimmyCarter** [comment]
I don't see why this can't be done, but it requires saving more of the parameters used to create the image in `dalle-flow` to be the easiest to implement. I want to start storing the conditioned latents, when I do that MR I can add the other parameters maybe?

**Comment by aaronsantiago** [comment]
Not sure what conditioned latents means--would that mean saving some part of the prompt to increase the speed of regenerations?

This could be related to the other request of tying the full prompt to each generation rather than the ID. In my mind, functionally what I want is to automatically have it type in the exact same command, just with the seed changed if there is one.

I could envision getting this feature (and displaying the prompt for each run) by having a dictionary holding each run's parameters, and simply rerunning the command with the same parameters if requested.

**Comment by AmericanPresidentJimmyCarter** [comment]
As I understand it prompting goes prompt -> tokens -> embeddings -> conditioned latents, then the conditioned latents are used to generate the image. Interpolate just does spherical interpolation of the conditioned latents. If the conditioned latent was re-supplied on riff you could avoid computing it again, not that it's very expensive, but it is some time and memory.

In tags we could `json.dumps` the parameters to string so that that every Document has the parameters used to generate the image through the API in tags. Documents are stored by the bot in the docarrays folder, so you could get that information from there.

**Comment by AmericanPresidentJimmyCarter** [comment]
Okay, I'll probably add this to `dalle-jina` soon (store all parameters and latent conditioning), after that I can add a "reroll" button.

**Comment by aaronsantiago** [comment]
Ah doing that in dalle flow definitely seems like a better solution. I'll hold off trying to hack JSON storage into yasd 😅
