### ISSUE TITLE
Resolutions producing varying results

### ISSUE THREAD

**Issue by AceBeaker2** [AmericanPresidentJimmyCarter/yasd-discord-bot#7]
Some resolutions do not work, here is a list
Square resolutions 512x512 and above = working
Square resolutions less than 512x512 = noisy, fuzzy, weirdly noisy
Any vertical or landscape resolutions = stretched into a square
Vertical or landscape resolutions less then 512x512 = noisy, fuzzy, weirdly noisy AND stretched into a square

Assuming all resolutions are multiples of 64
resolution edited in dalle/dalle-flow/executors/stable/config.yml

**Comment by AmericanPresidentJimmyCarter** [comment]
I will look into this, probably forgetting to set a variable somewhere.

**Comment by AmericanPresidentJimmyCarter** [comment]
So the reason that non-square resolutions do not work is because of how dalle-jina's DocArray serializes the image pictures. I will have to write my own code for creating the output images to allow users to make non-square resolution images. Originally the code had the ability to specify what resolution you wanted, but I didn't have time to fix the issue with DocArray. It will be coming in a future update.

**Comment by AmericanPresidentJimmyCarter** [comment]
Ok so I talked to a lot of people and all samplers have this issue. The model was trained with 512x512 and fares best with height or width >= 384.

Feel free to try my PR here: https://github.com/AmericanPresidentJimmyCarter/yasd-discord-bot/pull/18
